### ISSUE TITLE
Initial README content

### ISSUE THREAD

**Issue by cmgriffing** [cmgriffing/boat.world#10]
The README needs more specific content instead of the generic Gatsby boilerplate:

- Info about Bot.land
- Goals of the project
- Stream specific info:
  -- "do not review on stream" verbiage
  -- Github name public warning

**Comment by cmgriffing** [comment]
@technicalillusion Assigning to you :)

**Comment by Strik3ria** [comment]
Got it!

**Comment by cmgriffing** [comment]
**"do not review on stream" verbiage**

### "Do Not Review On Stream"

If you are feeling self conscious and would prefer not to have your PR reviewed directly on stream, make sure that you have the first sentence of the PR message read:
DO NOT REVIEW ON STREAM

**Comment by cmgriffing** [comment]
**Github name public warning**

### Warning: Public Information
Be warned that interacting with Github and Twitch together can reveal who you are more than you intended. If you wish to maintain anonymity, it might be worth it to create a "clean" account on either service.

**Comment by cmgriffing** [comment]
**Community Project Warning**

### Community Project Warning

This project is meant to be an open source learning process for various members of the Twitch programming community.  By contributing to this project you adhere to the LICENSE below and your contributions are open source as well.
