### ISSUE TITLE
Grab Image Assets

### ISSUE THREAD

**Issue by cmgriffing** [cmgriffing/boat.world#3]
We will need:

- the main logo
- the favicon
- bot image assets
- general screenshots
- focused screenshots if possible (if designs have been ironed out)

**Comment by andbrl** [comment]
Hi cmgriffing,  I have made pull request to add the favicons and logo. I don't really understand what do you mean by focused screenshots though? Would you be able to explain it to me a bit more? Thank you! :)

**Comment by cmgriffing** [comment]
Thanks for grabbing the images. Now we need to add them to the index.html file as meta tags and such so that various devices see it properly.
