### ISSUE TITLE
Dockerfile for platform-agnosticism

### ISSUE THREAD

**Issue by cmgriffing** [cmgriffing/boat.world#6]
Some users have experienced issues on various platforms. It would be nice to create an isolated docker environment for users so that the project does not interfere with their local environment.

**Comment by mtheoryx** [comment]
I would like to see someone take this on, and I can help.

If we get to a crunch, I could do this, but... I'd rather see someone new get some experience.

(roberttables from twitch here)

**Comment by cmgriffing** [comment]
Closing all issues as this project is now Archived.
