### ISSUE TITLE
Add favicon and app image meta tags to index head

### ISSUE THREAD

**Issue by cmgriffing** [cmgriffing/boat.world#9]
We need the meta tags for the newly created images. These images are used for various mobile devices. We should probably add these in the Layout component file.

See this link for favicon and meta tag help:
https://github.com/audreyr/favicon-cheat-sheet

See React Helmet docs for how to use Helmet to modify the `head` element: 
https://github.com/nfl/react-helmet/tree/release/5.2.0

**Comment by cmgriffing** [comment]
@oliva20 Tagging you so that I can assign this task for better tracking.

**Comment by andbrl** [comment]
I'll take this.

**Comment by cmgriffing** [comment]
Closing all issues as this project is now Archived.
